- name: Demo on fileVars
  hosts: all
  vars:
    url: "play.google.com"
  vars_files:
    - "{{ env }}-vars.yaml"
  tasks:
    - name: Printing variables from file
      ansible.builtin.debug:
        msg: "Current Environment is  {{ env }} and the team name is {{DEVLEAD}} the value is {{A}}"