- name: Demo on shell module
  hosts: all
  tasks:
    - name: Running a shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Printing the uptime output
      ansible.builtin.debug:
        msg: "The uptime is {{OUT.stdout}}"